function p = userpath
 
p = [...
     'codes:', ...
     'codes/interleavers:', ...
     'results:', ...
     'param:', ...
     'param/log:', ...
     'plots:', ...
     'tools:', ...
     '../:'];

